### ISSUE TITLE
Enable certificate verification to prevent MITM attacks

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-redis#15]
Currently the TLS/SSL offering for Heroku Redis uses self-signed certificates, meaning the connection is still vulnerable to MITM attacks.

I've filed a ticket requesting that the certificates be signed (eg using a custom CA cert):
https://help.heroku.com/tickets/396267

If/when that's resolved, this buildpack needs to be updated, to:
- Specify the CA cert using the `CAfile` option
- Enable verification using `verifyChain` / `verifyPeer` options

This may also require a newer version of openssl/stunnel.

For more details, see:
https://www.stunnel.org/static/stunnel.html#SERVICE-LEVEL-OPTIONS

**Comment by edmorley** [comment]
> I've filed a ticket requesting that the certificates be signed (eg using a custom CA cert):
> https://help.heroku.com/tickets/396267

For posterity, the replies on that ticket were (last one on 4th October 2016):

> Thanks for the feedback. We recognize that this is an issue. For us to do so requires two different things to happen. We first need to start creating our own domain names for all of the resources. So instead of seeing *.amazonaws.com in the config var you'd see something like *.herokudata.com. Once we accomplish that, then we'll be able to start creating certs on the resources. On the technical side of this, we're discussing how to pull all of the pieces together. This is a very big project for us that we won't be able to accomplish very quickly. I would recommend that we check in on this in a few months time to see where we're at. 

My reply:

> I agree that sounds like the best long-term solution, but can't a custom (ie self-generated) CA cert be used to sign the certificates in the meantime? That CA cert wouldn't be in the system certificate store, but the user could pass it in as part of configuring their Redis client. (eg like one has to do when connecting to RDS).
> This wouldn't require any domain name mapping changes, so wouldn't be as complex.

Rimas' reply to that:

> That might work. I know myself and the team have focused on the long term solution. We're going into planning in another month and I'll see what the level of effort is on something like this.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
We also just discovered heroku redis is serving a self-signed cert. Is there any update here, or any plans to address this?

**Comment by edmorley** [comment]
Since the ticket mentioned above, I filed another (https://help.heroku.com/tickets/511098) in September 2017, asking:

(Pleasantries trimmed for conciseness)

> A number of Mozilla's apps are currently using memcache (for example via the Memcachier addon) but would like to switch to Heroku Redis. A year ago I opened a few tickets for some problems I noticed with the current Heroku Redis TLS implementation which we would prefer to see resolve before we switch - and I was wondering if there had been any progress since?
> 
> Specifically regarding:
> 
>   1. Stopping using self-signed certificates (see ticket #396267 and heroku/heroku-buildpack-redis#15), either by:
> 
>       * Using a custom CA certificate (not present in the certificate system store) that is added to the buildpack and/or people's client settings in their app
>       * Switching from *.amazonaws.com to *.herokudata.com domains and thus being able to use a public CA (eg Let's Encrypt) to issue certs
> 
>   2. Avoiding having to manually adjust `REDIS_URL` to replace `redis://` with `rediss://` as well as needing to increment the port number by one to use the secure port. For example by adding an "Enforce secure Redis access" setting to the Heroku Redis web dashboard settings page, which (a) blocks the non-secure port, (b) makes `REDIS_URL` use the secure scheme/port instead. (See ticket # 396297)

Their reply:
> Unfortunately none of these have been implemented. There have been discussions around moving away from self-signed certificates, but no action has been take at this stage.

My reply:
> Is there an estimate of timeframe for the work? Has there been any reconsideration of trying the halfway position? (The first bullet of list item number 1 below)

Their reply (14th September 2017):
> I'm afraid that this work hasn't been scheduled as of yet. There have been some changes in the product team which works on our Data services such that this would be a good time to raise this issue again. I will definitely bring this into our next meeting but for the time being I don't have any more useful information for you. Apologies that I don't have any concrete answers for you on this.

**Comment by edmorley** [comment]
redis-py has just changed the default SSL verification mode, which means connections to Heroku Redis instances fail with default settings.

Any news on having custom certs?

**Comment by edmorley** [comment]
> redis-py has just changed the default SSL verification mode, which means connections to Heroku Redis instances fail with default settings.

Forgot to link to the upstream change:
https://github.com/andymccurdy/redis-py/pull/1017

> Any news on having custom certs?

I've opened a ticket to ask for the current status:
https://help.heroku.com/tickets/667970

**Comment by collimarco** [comment]
I was considering to move a large application to Heroku... then I realized that you must use `VERIFY_NONE` for the Redis client. This is completely not safe and it is a shame that you don't even mention that you are vulnerable to MITM attacks in [the docs](https://devcenter.heroku.com/articles/securing-heroku-redis). How is it possible that you haven't fixed this during all these years? Heroku is an interesting platform but this is a huge security bug. I will reconsider Heroku when this is fixed.

**Comment by collimarco** [comment]
Also worth to mention that an attacker (MITM) not only can read the data, but he can also get the `AUTH` key (Redis password) and thus connect to the public facing Redis at any time later and read, update or delete data in any way.

**Comment by mperham** [comment]
I can't believe this is still an issue 7 years later.

**Comment by edmorley** [comment]
Closing since this buildpack is now deprecated, as it's no longer required with Redis 6+'s native TLS feature:
https://devcenter.heroku.com/articles/heroku-redis#security-and-compliance

Note: The self-signed certificate issue remains however, and is tracked at:
https://github.com/heroku/roadmap/issues/148
