### ISSUE TITLE
Ability to provide a cert / PEM

### ISSUE THREAD

**Issue by aaronsevers** [heroku/heroku-buildpack-redis#18]
Great buildback! Any plans to allow a PEM to be provided for stunnel via ENV so this buildpack could be used for things besides Heroku Redis without needing to fork it?

**Comment by edmorley** [comment]
Closing since this buildpack is now deprecated, as it's no longer required with Redis 6+'s native TLS feature:
https://devcenter.heroku.com/articles/heroku-redis#security-and-compliance
