### ISSUE TITLE
Consider overriding process entries

### ISSUE THREAD

**Issue by tt** [heroku/heroku-buildpack-redis#4]
Should the buildpack automatically override process entries? This would eliminate any other changes than configuring the buildpack.

(I'm not sure if there is a significant penalty of always setting up the tunnel.)

**Comment by cyberdelia** [comment]
Could be a good idea, I wonder how does one can override theses entries ? :expressionless:

**Comment by tt** [comment]
@cyberdelia:

```
cat Procfile | sed 's/:/: bin\/start-stunnel/' >Procfile.new
```
