### ISSUE TITLE
Redis tunneling not working with Go programs?

### ISSUE THREAD

**Issue by shosti** [heroku/heroku-buildpack-redis#6]
Hi! Let me know if I'm doing something obviously wrong, but I've been trying to get a Go app up and running with Redis using this buildpack, and I'm never able to connect to `REDIS_URL`. At first I though it might be an issue with the [redigo library](https://github.com/garyburd/redigo), but it looks like it's actually lower level.

Steps to reproduce:
1. Create minimal Go app with code like https://play.golang.org/p/m8qfyWe3LZ and Procfile https://gist.github.com/488fb7dd761af5a4cdf3
2. Create heroku app with the heroku-redis addon
3. `heroku buildpacks:set https://github.com/heroku/heroku-buildpack-redis`
4. `heroku buildpacks:add https://github.com/heroku/heroku-buildpack-go`
5. `heroku config:set STUNNEL_ENABLED=false` (as a base case)

output:
https://gist.github.com/46c9a425dcad45a9f178 (expected)
1. `heroku config:set STUNNEL_ENABLED=true`

output:
https://gist.github.com/ee9ca9175030d1f6f0e4 (specifically "connection refused")

This was run on free-tier app and redis, but in production I was seeing the same error with Standard-1X worker dynos and Premium 5 heroku-redis.

**Comment by cyberdelia** [comment]
Which redis plan are you using here?

**Comment by cyberdelia** [comment]
Could you also share your app name test or open a support ticket?

**Comment by shosti** [comment]
@cyberdelia For this test, I used the free tier heroku-redis, but I was getting an identical error in production with the Premium 5 plan (app name is doodle-prd). I'll open up a support ticket as well.

**Comment by cyberdelia** [comment]
hobby-dev plans don't support stunnel.

**Comment by shosti** [comment]
I just tried the same with Standard-1X dyno and Premium 0 heroku redis. Results were basically identical: https://gist.github.com/fbb9b146f4190691e90c

**Comment by cyberdelia** [comment]
My QA app for this buildpack is in Go, so this is very strange, did you open a support ticket? Feel free to share your ticket number here.

**Comment by shosti** [comment]
@cyberdelia ticket number is 280605
