### ISSUE TITLE
Warning: `Update OpenSSL shared libraries or rebuild stunnel`

### ISSUE THREAD

**Issue by carlosantoniodasilva** [heroku/heroku-buildpack-redis#9]
I'm trying this buildpack to connect to Heroku Redis using a premium-0 plan on a test app here, and it seems stunnel starts successfully, I can see the enabled output on my logs:

```
app web.1 - - buildpack=stunnel at=stunnel-enabled
...
app web.1 - - buildpack=stunnel at=stunnel-start
```

And the app seems to be working fine, however I also have the following on my logs:

```
2015.10.09 20:48:03 LOG5[21:139662156998464]: stunnel 4.53 on x86_64-pc-linux-gnu platform
2015.10.09 20:48:03 LOG5[21:139662156998464]: Compiled with OpenSSL 1.0.1e 11 Feb 2013
2015.10.09 20:48:03 LOG5[21:139662156998464]: Running with OpenSSL 1.0.1f 6 Jan 2014
2015.10.09 20:48:03 LOG5[21:139662156998464]: Update OpenSSL shared libraries or rebuild stunnel
2015.10.09 20:48:03 LOG5[21:139662156998464]: Threading:PTHREAD SSL:+ENGINE+OCSP Auth:LIBWRAP Sockets:POLL+IPv6
2015.10.09 20:48:03 LOG5[21:139662156998464]: Reading configuration from file vendor/stunnel/stunnel.conf
```

This tells me something is not right with the buildpack/stunnel installation, it seems to have been compiled against a different version of OpenSSL. Version `1.0.1f 6 Jan 2014` is the one available with `heroku bash`:

```
~ $ openssl version
OpenSSL 1.0.1f 6 Jan 2014
```

Can I test-drive running this using a free dyno, or do I need at least a professional 1X dyno? Is there anything I'm missing? I'd appreciate any pointers on this, thanks!

**Comment by cyberdelia** [comment]
This is an harmless message, indicating that our stunnel binary is effectively running against a newer openssl, this will not affect stunnel behaviour nor your application behavior.

**Comment by carlosantoniodasilva** [comment]
@cyberdelia thanks, we were thinking the exact same thing, but the warning is confusing anyway. We'll see how it goes.
